export default {
  backgroundImage: require("./MaskheaderBackground.png"),
  profilePic: require("./avatarprofile.png"),
  avatar: require("./avatar.png"),
  headerSettingsIcon: require("./headerSettingsIcon.png"),
  headerSearchIcon: require("./headerSearchIcon.png"),
  gainArrow: require("./gainArrow.png"),
  lostArrow: require("./arrow-up-10.png"),
  bgTest: require("./Mask.png"),
  headerBackButton: require("./headerBackButton.png"),
  followsYouOk: require("./followsYouOk.png"),
  youFollowOk: require("./youFollowOk.png"),
  tabIndex0: require("./tabIndex0.png"),
  tabIndex1: require("./tabIndex1.png"),
  tabIndex2: require("./tabIndex2.png"),
  tabIndex3: require("./tabIndex3.png"),
  tabIndex0Active: require("./tabIndex0Active.png"),
  tabIndex1Active: require("./tabIndex1Active.png"),
  tabIndex2Active: require("./tabIndex2Active.png"),
  tabIndex3Active: require("./tabIndex3Active.png"),

};
